name: Cron Job

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"

jobs:
  print-hello-cron:
    runs-on: macos-latest
    steps:
      - name: Print message
        run: echo "Hello Cron!"
