name: Cron Job

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  print-hello-cron:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print message
        run: echo "Hello Cron!"
      - name: Run script
        run: node print.js
