name: Cron Job

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  print-hello-cron:
    runs-on: macos-latest
    steps:
      - name: Print message
        run: echo "Hello Cron!"

  execute-script:
    runs-on: macos-latest
    needs: print-hello-cron
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: node print.js

  curl-endpoint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: cURL server (GET)
        run: |
          node print.js &
          curl -X GET http://localhost:8080
      - name: cURL server (POST)
        run: |
          node print.js &
          curl -X POST http://localhost:8080
